services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: authconnect
      POSTGRES_USER: authconnect
      POSTGRES_PASSWORD: 21122002
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
      # - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U authconnect -d authconnect"]
      interval: 10s
      timeout: 5s
      retries: 3

  migrate:
    image: migrate/migrate:latest
    command: ["-path=/migrations", "-database=postgres://authconnect:21122002@postgres:5432/authconnect?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      ENV: production
      DSN: postgres://authconnect:21122002@postgres:5432/authconnect?sslmode=disable
      JWT: PEgCMaqOZ8NJsy6IXPdzIMRwPxvRWQafcNmUtveTDOSxGOInVh3j6zcgLgKEocqW
    depends_on:
      - migrate

volumes:
  psql_volume:
