apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: postgres
spec:
  template:
    spec:
      containers:
      - name: migration
        image: migrate/migrate:latest
        command: [
          "migrate",
          "-path=/migrations",
          "-database=postgres://authconnect:authconnect2024@postgres:5432/authconnect?sslmode=disable",
          "up"
        ]
        volumeMounts:
        - name: migration-volume
          mountPath: /migrations
      restartPolicy: OnFailure
      volumes:
      - name: migration-volume
        hostPath:
          path: migrations
