apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  ports:
    - port: {{.Values.port}}
      targetPort: {{.Values.port}}
      protocol: TCP
  selector:
    app: postgres
