apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  labels:
    app: backend
    tier: backend
  namespace: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
      tier: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ENV
        - name: DSN
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DSN
        - name: JWT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: JWT
        - name: ORIGIN
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ORIGIN
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SMTP_PORT
        - name: SMTP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SMTP_PASSWORD
