apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend
  labels:
    app: postgres
    tier: backend
  namespace: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
      tier: backend
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.port }}
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ENV
        - name: DSN
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DSN
        - name: JWT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: JWT
